import React from 'react';
import { HomeInterface } from './HomeInt';
import './Home.css';
import logo from './Lab Logo.png';

export function HomePage({ setCurrPage, setIsApiKeyValid }: HomeInterface) {
    return (
        <div className="HomeBackground">
            <div className="container text-center">
                <img src={logo} alt="logo" id="logo" />
                <h1>Welcome to Career Labs!</h1>
                <div className="quiz_selection_widget">
                    <h1>Choose a Quiz!</h1>
                    <div className="text-content">
                        <div className="choice-card">
                            <h2>A Quick Test</h2>
                            <div className="nav-buttons">
                                <button onClick={() => setCurrPage(1)}>Short Quiz</button>
                            </div>
                            <p>In this quiz, you will be given a few questions where you will answer based on agreement or disagreement, then we will assess your answers and suggest a career based on what might fit the best.</p>
                        </div>
                        <div className="choice-card">
                            <h2>The Long Test</h2>
                            <div className="nav-buttons">
                                <button onClick={() => setCurrPage(2)}>Long Quiz</button>
                            </div>
                            <p>In this quiz, you will be given a few short answer questions where you can give more descriptive answers yourself for a chance at a more accurate assessment of the career that you are looking for.</p>
                        </div>
                    </div>
                </div>
                <div className="Results-choice-card">
                    <h2>Check Your Results</h2>
                    <div className="nav-buttons">
                        <button onClick={() => setCurrPage(3)}>Result</button>
                    </div>
                    <p>Use this button to see the career that we have picked out for you.</p>
                    <p>(Disclaimer, the results from this page are generated by AI using OpenAI, so the results may or may not be formatted weirdly.)</p>
                </div>
                <div>
                    <button onClick={() => setIsApiKeyValid(false)} className="change-api-key">Change API Key</button>
                </div>
                                
                <footer className="home-footer" style={{ textAlign: "center", fontStyle: "italic", marginTop: "20px", backgroundColor: "#575a8d", fontWeight: "bold"}}>
                    Website by: Zhihua Sun, Connor Chipoletti, Ray Fischer
                </footer>
            </div>
        </div>
    );
}

export default HomePage;
